# Generated by Django 2.0.2 on 2018-02-17 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import autoslug.fields
import ndh.models

import cagnottesolidaire.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cagnotte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('image',
                 models.ImageField(blank=True, upload_to=cagnottesolidaire.models.upload_to_proj,
                                   verbose_name='Image')),
                ('objectif', models.TextField(verbose_name='Description de l’objectif de la cagnotte')),
                ('finances',
                 models.DecimalField(decimal_places=2,
                                     max_digits=8,
                                     validators=[cagnottesolidaire.models.validate_positive],
                                     verbose_name='But à atteindre')),
                ('fin_depot',
                 models.DateField(help_text='format: 31/12/2017',
                                  validators=[cagnottesolidaire.models.validate_future],
                                  verbose_name='Date de fin du dépôt des propositions')),
                ('fin_achat',
                 models.DateField(help_text='format: 31/12/2017',
                                  validators=[cagnottesolidaire.models.validate_future],
                                  verbose_name='Date de fin des achats')),
                ('responsable',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(ndh.models.Links, models.Model),
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('cagnotte',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cagnottesolidaire.Cagnotte')),
                ('demandeur',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valide', models.NullBooleanField(default=None, verbose_name='validé')),
                ('paye', models.BooleanField(default=False, verbose_name='payé')),
                ('remarques', models.TextField(blank=True)),
                ('prix',
                 models.DecimalField(decimal_places=2,
                                     max_digits=8,
                                     validators=[cagnottesolidaire.models.validate_positive])),
                ('beneficiaire',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('paye', 'valide', 'proposition'),
            },
            bases=(ndh.models.Links, models.Model),
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('description', models.TextField()),
                ('prix',
                 models.DecimalField(decimal_places=2,
                                     max_digits=8,
                                     validators=[cagnottesolidaire.models.validate_positive])),
                ('beneficiaires',
                 models.IntegerField(default=1,
                                     help_text='0 pour un nombre illimité',
                                     validators=[cagnottesolidaire.models.validate_positive],
                                     verbose_name='Nombre maximal de bénéficiaires')),
                ('image',
                 models.ImageField(blank=True, upload_to=cagnottesolidaire.models.upload_to_prop,
                                   verbose_name='Image')),
                ('cagnotte',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cagnottesolidaire.Cagnotte')),
                ('responsable',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('cagnotte', 'prix'),
            },
            bases=(ndh.models.Links, models.Model),
        ),
        migrations.AddField(
            model_name='offre',
            name='proposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cagnottesolidaire.Proposition'),
        ),
    ]
