# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 12:34
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import cagnottesolidaire.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valide', models.NullBooleanField(default=None, verbose_name='validé')),
                ('paye', models.BooleanField(default=False, verbose_name='payé')),
                ('remarques', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8, validators=[cagnottesolidaire.models.validate_positive])),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('paye', 'valide', 'proposition'),
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nom', unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to=cagnottesolidaire.models.upload_to_proj, verbose_name='Image')),
                ('objectif', models.TextField(verbose_name='Description de l’objectif de la cagnotte')),
                ('finances', models.DecimalField(decimal_places=2, max_digits=8, validators=[cagnottesolidaire.models.validate_positive], verbose_name='But à atteindre')),
                ('fin_depot', models.DateField(help_text='format: 31/12/2017', validators=[cagnottesolidaire.models.validate_future], verbose_name='Date de fin du dépôt des propositions')),
                ('fin_achat', models.DateField(help_text='format: 31/12/2017', validators=[cagnottesolidaire.models.validate_future], verbose_name='Date de fin des achats')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nom', unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8, validators=[cagnottesolidaire.models.validate_positive])),
                ('beneficiaires', models.IntegerField(default=1, help_text='0 pour un nombre illimité',
                                                      validators=[cagnottesolidaire.models.validate_positive], verbose_name='Nombre maximal de bénéficiaires')),
                ('image', models.ImageField(blank=True, upload_to=cagnottesolidaire.models.upload_to_prop, verbose_name='Image')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cagnottesolidaire.Projet')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('projet', 'prix'),
            },
        ),
        migrations.AddField(
            model_name='offre',
            name='proposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cagnottesolidaire.Proposition'),
        ),
    ]
