# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cagnottesolidaire', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projet',
            new_name='Cagnotte',
        ),
        migrations.AlterModelOptions(
            name='proposition',
            options={'ordering': ('cagnotte', 'prix')},
        ),
        migrations.RenameField(
            model_name='proposition',
            old_name='projet',
            new_name='cagnotte',
        ),
    ]
