# Generated by Django 3.2.5 on 2021-07-20 19:23

import cagnottesolidaire.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cagnottesolidaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cagnotte',
            name='fin_achat',
            field=models.DateField(validators=[cagnottesolidaire.models.validate_future],
                                   verbose_name='Date de fin des achats'),
        ),
        migrations.AlterField(
            model_name='cagnotte',
            name='fin_depot',
            field=models.DateField(validators=[cagnottesolidaire.models.validate_future],
                                   verbose_name='Date de fin du dépôt des propositions'),
        ),
        migrations.AlterField(
            model_name='cagnotte',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='valide',
            field=models.BooleanField(default=None, null=True, verbose_name='validé'),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
