# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 14:41
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cagnottesolidaire', '0002_rename_projet_cagnotte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('cagnotte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cagnottesolidaire.Cagnotte')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
