language: python
dist: xenial
sudo: required
python:
  - 3.6
services:
  - postgresql
install:
  - pip install pipenv
  - pipenv install --deploy --dev
env:
  - SECRET_KEY='pipo' EMAIL_HOST_PASSWORD='pipo' POSTGRES_HOST='localhost' POSTGRES_PASSWORD='' RAVEN=True DSN=''
script:
  - ./manage.py migrate
  - coverage run manage.py test
  - flake8 .
  - yapf -dr .
  - safety check
  - pip install "git+https://github.com/${TRAVIS_REPO_SLUG}.git#egg=cagnottesolidaire"
after_success:
  - coveralls
