version: '3'

services:
  postgres:
    image: postgres:11-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - "${CHATONS_ROOT_DIR:-/srv/chatons}/cagnottesolidaire/sql:/var/lib/postgresql/data"
  memcached:
    image: memcached:alpine
    restart: unless-stopped
  app:
    build: .
    restart: unless-stopped
    volumes:
      - "${CHATONS_ROOT_DIR:-/srv/chatons}/cagnottesolidaire/srv:/srv"
    env_file:
      - .env
    environment:
      - DB=postgres
      - MEMCACHED=True
    networks:
      - web
      - default
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host: cagnottesolidaire.${DOMAIN_NAME:-io}, www.cagnottesolidaire.${DOMAIN_NAME:-io}"
  nginx:
    image: nim65s/ndh:nginx
    restart: unless-stopped
    volumes:
      - "${CHATONS_ROOT_DIR:-/srv/chatons}/cagnottesolidaire/srv/cagnottesolidaire:/srv"
    networks:
      - web
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host: cagnottesolidaire.${DOMAIN_NAME:-io}, www.cagnottesolidaire.${DOMAIN_NAME:-io}; PathPrefix: /static, /media"

networks:
  web:
    external: true
