# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 21:05
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import autoslug.fields

import projets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valide', models.NullBooleanField(default=None, verbose_name='validé')),
                ('paye', models.BooleanField(default=False, verbose_name='payé')),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nom', unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('jumbo', models.ImageField(blank=True, upload_to=projets.models.upload_to_jumbo, verbose_name='Grande image')),
                ('pict', models.ImageField(blank=True, upload_to=projets.models.upload_to_pict, verbose_name='Petite image')),
                ('objectif', models.TextField(verbose_name='Description de l’objectif de la cagnotte')),
                ('finances', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='But à atteindre')),
                ('fin_depot', models.DateField(help_text='format: 31/12/2017', verbose_name='Date de fin du dépôt des propositions')),
                ('fin_achat', models.DateField(help_text='format: 31/12/2017', verbose_name='Date de fin des achats')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nom', unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8)),
                ('beneficiaires', models.IntegerField(default=1, help_text='0 pour un nombre illimité', verbose_name='Nombre maximal de bénéficiaires')),
                ('image', models.ImageField(blank=True, upload_to=projets.models.upload_to_prop, verbose_name='Image')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.Projet')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='offre',
            name='proposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.Proposition'),
        ),
    ]
