# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offre',
            options={'ordering': ('paye', 'valide', 'proposition')},
        ),
        migrations.AlterModelOptions(
            name='proposition',
            options={'ordering': ('projet', 'prix')},
        ),
    ]
