# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import projets.models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0002_offre_remarques'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[projets.models.validate_positive]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projet',
            name='fin_achat',
            field=models.DateField(help_text='format: 31/12/2017', validators=[projets.models.validate_future], verbose_name='Date de fin des achats'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='fin_depot',
            field=models.DateField(help_text='format: 31/12/2017', validators=[projets.models.validate_future], verbose_name='Date de fin du dépôt des propositions'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='finances',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[projets.models.validate_positive], verbose_name='But à atteindre'),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='beneficiaires',
            field=models.IntegerField(default=1, help_text='0 pour un nombre illimité', validators=[projets.models.validate_positive], verbose_name='Nombre maximal de bénéficiaires'),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[projets.models.validate_positive]),
        ),
    ]
