name: Tests

on: [push, pull_request]

env:
  SECRET_KEY: pipo
  EMAIL_HOST_PASSWORD: pipo
  POSTGRES_HOST: postgres
  POSTGRES_PASSWORD: postgres
  RAVEN: False
  DSN: ""

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: poetry
      - name: setup
        run: poetry install --with dev --with prod --no-interaction --no-ansi
      - run: poetry run ./manage.py migrate
        env:
          PYTHONWARNINGS: error
      - run: poetry run coverage run manage.py test
        env:
          PYTHONWARNINGS: error
      - run: python -m pip install "git+https://github.com/${GITHUB_REPOSITORY}.git#egg=cagnottesolidaire"

      - uses: codecov/codecov-action@v3
